### ISSUE TITLE
consistent file extensions

### ISSUE THREAD

**Issue by ibaned** [SNLComputation/Albany#113]
Right now Albany uses a combination of `.h`, `.hpp`, `.cc`, and `.cpp` files. This makes writings scripts and doing general development more difficult. We should have all files be either `.hpp` or `.cpp`.

**Comment by lxmota** [comment]
I'm the culprit behind the use of .h and .cc, which to my knowledge were the most pervasive extensions in the UNIX world when C++ started to become popular.

That said, I like the NOX convention of using .H and .C, so I vote for .H for headers and .C for source files.

Many, many years ago I wrote programs for MS Windows (ick!) where the extensions .hpp and .cpp were _de rigueur_. I was traumatized by that, so I now kind of hate that convention. Same with the infamous Hungarian convention.

**Comment by ibaned** [comment]
My issue with `.h` is its indistinguishable from pure C header files, in fact the `vim` editor will highlight it only as C code. That is fine for headers that can be used from C (just config macros), but for C++ a different extension is needed.

I've used `.hpp` and `.cpp` in personal projects, so I have them associated with decent code as opposed to MS Windows code. They also seem to be far and away the most common extension in Trilinos.

At the end of the day this is an arbitrary choice, and I'd prefer to go with the current majority by file count, which should be representative of what most developers prefer.

**Comment by lxmota** [comment]
For LCM we decided that we would follow the Google Style Guide:

https://google.github.io/styleguide/cppguide.html

That calls for using .h for headers and .cc for sources. I agree that .h is confusing for C/C++, so that's why I was suggesting to use .H and .C like NOX.

We can change all extensions to be .hpp and .cpp if that makes things easier. But just because something is used in Trilinos doesn't mean that it is necessarily good.

For example, I read that the naming convention for classes, variables and other things in Trilinos (or at least the original core packages) is that of Java. That seems to be insufficient to distinguish between function names and variable names in C++. The widespread use and abuse of Teuchos::RCP clearly mimics the way Java deals with memory allocation.

And so, thinking that Google coders know a thing or two about programming, we decided to follow their style guide.

Anyway, sorry for the digression. Food for thought for another time.

**Comment by ibaned** [comment]
The Google Style Guide is a great contribution to C++, and I definitely follow most of what is in there. I still can't escape the syntax highlighting issue for `.h`, though.

I agree with using our judgement over copying Trilinos, for example I've been happy moving from `TEUCHOS_TEST_FOR_EXCEPTION` to `ALBANY_ASSERT`.

This seems to be a mostly subjective choice, so I think we'll end up voting among Albany members similar to what we did for the organization name (and learning from our mistakes, lets not submit our decision for high-level managers to approve this time).

**Comment by bartgol** [comment]
I agree that the topic is mainly subjective. But since we're talking, I'll share my opinion together with my reasoning behind my personal tastes.

For headers, I agree with Dan on the fact that `.h` should be used only for pure C headers, or at least C-compatible headers (such as config files). A different extension is helpful to distinguish C++ code, both in terms of recognizing what language a file stores without opening it, and also in terms of text editor highlight.

As for the `.cc` vs `.cpp` vc `.C` vs `.cxx` vs `.c++` vs...: the former may probably come from 'C with Classes', an ancient name for C++ which probably not many developers recall being the original name that Stroustrup gave to the new language. Besides that, seeing `.cc` reminds me of gcc and mpicc, which are the C version of the GNU/MPI compilers. `.cpp` is arguably the most common extension, and I probably it's the one I like the most (perhaps cause I'm used to it). I dislike `.c++` since, although it reminds of g++, it's hard to type the + sign (requires a shift). `.cxx` reminds of mpicxx, but is not very common. Finally, `.C` is indeed used in a few project (notably for us, NOX), but I still find it too similar to `.c` (besides requiring to hit shift, which I never liked).

Besides all of that, it ultimately boils down to habits. Having seen an extension for years makes you more comfortable with it. So it is a matter of tastes. However, for the sake of Albany's future I would argue to use the extension that future developers are more likely to associate to C++ headers/sources and be comfortable with.

**Comment by lxmota** [comment]
@bartgol Fair enough. Your argument that .C and .H require pressing shift is convincing to me. :)
@ibaned I'm happy with going ahead and making .hpp and .cpp the "official" extension for Albany.

Now I'm spamming @agsalin @gahansen @ikalash @mperego @jtostie @djlittl @jwfoulk @calleman21 @bgranzow to see if they care one way or another and move forward with this.

**Comment by jtostie** [comment]
I don't care about the convention as long as we are consistent everywhere.

**Comment by bgranzow** [comment]
I'll throw a vote in for `.hpp` and `.cpp`. I _think_ most of the files in Albany already have those extensions, so switching all files to those extensions should have the smallest delta in the history (if that even matters).

**Comment by mperego** [comment]
I'm also for .hpp .cpp. Thanks.

**Comment by djlittl** [comment]
No strong feelings from me on this.  I'll go with the flow.

**Comment by lxmota** [comment]
Changed a long time ago, and also irrelevant now because of LCM fork.
