### ISSUE TITLE
Volumeric type boundary conditions

### ISSUE THREAD

**Issue by hillyuan** [SNLComputation/Albany#300]
Volumeric type external loads consist of Gravity, Centrifugal force, Earthquack acceleration etc. for mechanical analysis or heat generation in heat analysis. It is quite like current Neumann boundary condition which provide rhs contribution on systame equation but should integrate upon elemental volume. On the other hand, Albany provides source functions for heat analysis, but I don't think its design is adaquate for the above general volumeric type boundary conditions.

**Comment by bartgol** [comment]
Volumetric terms can be added as 'normal' source terms. The boundary conditions factory is a quite involved design, so sneaking a volumetric bc in could be problematic.

**Comment by ibaned** [comment]
Yes, I think by definition these are not "boundary" conditions, since they don't act on just the boundary.

**Comment by djlittl** [comment]
The body force in that input file only gets applied to the peridynamic portion of the model.  The input deck is for a coupled Albany/Peridigm simulation, and the functionality for applying the body force lives in Peridigm.  It can be constant, or a user-defined function of time and space.  When I ran this problem I used a huge hack to manually put the body force on the Albany side (literally typed it in the source code).

**Comment by djlittl** [comment]
And I agree that "boundary condition" is a misnomer, but I don't lose sleep over these things.  In Peridigm, functionality of this type lives in the BoundaryAndInitialConditionManager, which is pretty verbose and is still wrong for body forces.  I guess I could call it the BoundaryAndInitialConditionAndBodyForceManager to cover all the bases.

**Comment by hillyuan** [comment]
1. I have noticed some relevent implementation, for example, "Gravity Acceleration" definition of "Basal boundary condition for FELIX". But as above @djlittl indicated, it seems like that it is applicable for some specific cases. I think it is really a FUNDAMENTAL function for FEM software and should be implemented as a common function of Albany.
2. It seems not a good idea to call it boundary condition. But should we call it a "source" term?  It is generally called distributed load, e.g, in Abaqus.
3. I am not quite understand what @bartgol 's "The boundary conditions factory is a quite involved design" mean. In fact, it is basically the same with current Neumman condition in Alabny besides their difference in quadrature domains. I am agree with the suggestion that it could be can be added as 'normal' source terms, but the problem is 1) It may needs a lots of modification on current "Source Functions" implementation? 2) I think "Source Functions" is defined as materialDB, is it adaquate to define it as a material property?

At last, I think the above volumeric load is quite fundamental. It is hoped that Albany developement team should proposed a basic design for its implementation.

**Comment by bartgol** [comment]
@hillyuan What I meant with that comment is that we may need to modify the factory logic, or hack into it, to allow to have the ability to have bc's defined on nodesets.

I still claim that it should be separated from the BC framework though. You may claim that although it's not a BC, putting it there won't be such a big deal. However, one _must_ consider readability of the library for _new_ users/developers. Keeping it organized and clean is a huge help there. Also, when first facing a new piece of code, I always keep into account the name of the class, file and folder that it is in, in order to figure out what the code does and where it is possibly used.
If anything has the name 'boundary' in it, I do expect it to act on an (N-1)-dimensional manifold, not on an N-dimensional part of the N-dimensional mesh.
Besides, I don't see such a difficulty in adding a new PHAL evaluator, separated from BC's. Perhaps we can put it in evaluator/utility (just like PHAL_Source), and call it PHAL_DistributedLoad, or something like that. If a problem needs it, it can create the PHAL evaluator (just like any other evaluator) during the volume field manager creation. This way, it would still be a 'common evaluator' in Albany, without affecting the bc logic.

**Comment by bartgol** [comment]
Closing for lack or response.
