### ISSUE TITLE
Code duplication in Albany_SolverFactory.cpp

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#40]
There is a lot of code duplication in Albany_SolverFactory.cpp, in particular having to do with creating a linearSolverBuilder for different physics that have their own model evaluators.  This should be cleaned up.

**Comment by bartgol** [comment]
True. albanyApp is created different times in different createXYZ routines. One version of createAlbanyApp should be enough. The app can then be passed to other createXYZ methods. I think the creation of Application, Solver and Model should be kept separated for clarity.

The method 'createAndGetAlbanyApp' sounds to me as 'create the app, then return it', while it returns the solver.

I would favor an interface like this:

RCP<Albany::Application> createAlbanyApp(params,comm...);
RCP<Albany::ModelEvaluator> createModel (app,...);
RCP<Albany::ModelEvaluatorT> createModelT (app,...);
RCP<Thyra::ModelEvaluator> createSolver(model,...);

I would also consider putting these as free functions rather than methods of a class, or at least static methods, since it does not need to live as an object. The only case where its status is reused after creating the solver (as far as I can see) is when the checkXYZResults[T] methods are called. Even then, I would argue that those methods do not belong conceptually in a solver factory, and could be free functions (in another header).

**Comment by bartgol** [comment]
I think this got fixed at some point, cause it seems much cleaner now.
