### ISSUE TITLE
Determine status of nightly Trilinos tests with Clang compiler 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#436]
If Trilinos isn't testing with Clang, try to get them to test with it.  Albany tests with Clang, and at least a few us believe this is an important compiler to keep in the nightlies, but if Trilinos doesn't officially support it, there may be difficulties getting Trilinos issues fixed that show up only in Clang builds.

**Comment by mperego** [comment]
There is a Trilinos nightly using Clang:
https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4600210

It's not part of the PR testing, but it should have high priority being part of ATDM

**Comment by mperego** [comment]
Oh.. but they are only building the Tpetra stack

**Comment by mperego** [comment]
@ikalash, I asked Ross Bartlett about adding a Trilinos Clang build as part of the PR testing. He said they plan to do so, but there is no clear time-frame. One issue is that currently the sems modules support only an old version of Clang.
What about suspending the Clang testing in Albany until Trilinos add a Clang build to the PR testing?

**Comment by ikalash** [comment]
Thanks for looking into it @mperego .  I guess my inclination would be to keep the tests since we have them and they are more or less clean, but take their output with a grain of salt until Trilinos is testing with clang. I see there is a SART meeting later this morning - maybe we can bring this up.

**Comment by mperego** [comment]
Yes, we can bring this up at the Trilinos SART meeting if there is time.
I understand your point but I think we should not test Albany with compilers that are not part of the Trilinos testing. Unfortunately we cannot afford it.

**Comment by bartgol** [comment]
@ikalash I'm also for turning it off, and turning it back on if/when Trilinos supports clang. The reason is that we already have too many builds to check, and you know how painful and time consuming that is. I don't think I'm going to dedicate any of my time to a build that may be wrong because of compiler issues...

**Comment by bartgol** [comment]
I'm closing this, since the Trilinos team has no short term plan to support Clang. They might in the future though, since I _think_ AMD plans to rely on it.

We can keep our Clang builds, if you want, but I'm not going to spend time to fix issues related to Clang itself.

For this reason, I think the Clang build(s) should use _the same_ configuration of some other build. In other words, we should _not_ test new configurations on Clang builds.

**Comment by ikalash** [comment]
@bartgol : why do you say the Trilinos team has no plan to support Clang?  At the last few SART meetings, they were working on setting up clang builds and my impression is it was near completion.  Sorry for not posting that info here.

I disagree with turning off the clang builds...  I think they reveal / have revealed real issues...  if we want to punt on the FPE issue (#486) I would say we can turn FPE checking off in the clang release build.  Curiously enough the FPEs seem to only show up in release, not debug, mode.

**Comment by bartgol** [comment]
> why do you say the Trilinos team has no plan to support Clang?

Office-mate conversation. Perhaps not the most accurate? I had the impression that Trilinos _will_ support Clang at some point, but that it was not clear when. Do you have more accurate information, for instance about time line?
