### ISSUE TITLE
remove Hydride

### ISSUE THREAD

**Issue by ibaned** [SNLComputation/Albany#46]
@gahansen more or less owns this code and we're fairly sure it no longer builds. Based on discussion this afternoon we will soon remove Hydride.

**Comment by gahansen** [comment]
It turns out that some of the problems in the "Hydride" set are actually still nightly tested on many of the dashboards, and the results look quite good. Many thanks to @ikalash for adding the Tempus time integrator capability to these problems! 

I'll assign myself to clean this up. Further, these problems probably do not merit their own directory at the src/ level; I'll work with the other projects and find them a home. This problem set contains a Cahn-Hilliard equation solve that might be interesting to other (potential) Albany users at some point.
