### ISSUE TITLE
Mesh change during simulation

### ISSUE THREAD

**Issue by RuixiongHu** [SNLComputation/Albany#491]
Hello Sandia expert,

Can I ask some questions about what to account for mesh changes during the simulation?

The case is, I'm working on a level set type of job. Thus in the middle of my simulation, I extracted the state variable array and set it on the mesh so that I could update the field with respect to the mesh geometry, and later send the updated field back to Albany's `state_Arrays`. I'm using the functions `copyQPStatesToAPF()` and `copyQPStatesfromAPF()` under src/disc/pumi to do the communication. Seems that the mesh entity are stored in something called `Bucket` in order to map to the `stateArray`.

However, my method involves some function that recover a qp field into a nodal field, which tend to do migrations on the mesh. So some of the mesh elements on the boundary will be migrated into its neighbor rank in order to finish the calculation. 

So clearly before and after this function, the mesh has been changed and the data stored inside `Bucket` expired. 

I think this is somewhat similar to a mesh adaptation work, except for the only thing changed is the ownership of some elements. That's saying, the mesh elements are still the same, except for the way they're split into ranks have been changed.

I would like to know about how Albany account for the mesh change so that in the middle of the simulation, the calculated solution vector and state variable arrays could still be correctly associated with the mesh.

I'll really appreciate any hint or help, and I would like to hear some advice from Brian @bgranzow since he wrote the function that do the field recover work.

Thanks!
Ruixiong

**Comment by bartgol** [comment]
Do you mean that if you ran with just one mpi rank, the mesh would be unchanged? If that's the case, I think there _may_ be a way of doing it, but not 100% sure.

The problem with changing the mesh on a single rank is that all the maps become invalid. I am not sure if we test this case or not. My guts tell me you're out of luck, but I've never worked on mesh adaptation in albany, so I may be wrong.

**Comment by RuixiongHu** [comment]
Hi Luca,

Yes the mesh will stay the same if running with one rank. So my code is working perfectly for a serial mesh.

To be more specific, the entire mesh itself (to be considered as a whole) has nothing changed, its size, number, topology etc are all remaining the same. The only thing that's changed is which process owns the control over it (as ownership).  Such as I have four integer 1 2 3 4, previously they're split as (1,2) and (3,4), but after the change they're split as (1,2,3) and (4).

So I wonder if you know any easy ways to do it? 
Thanks!

**Comment by bartgol** [comment]
We are already doing mesh rebalancing in some cases, but we do it only during the initialization (see IossSTKMeshStruct) if the mesh is given as a serial file.

My fear is what happens to solvers: all the thyra (be that tpetra or epetra) maps/vectors/matrices become invalid. If we _always_ queried the app/disc for maps before _every_ call to solver (and if the solvers had no memory), then we _could_ make it work. But I don't think this is what happens. Solvers keep internal variables around, they do not rebuild everything from scratch. Perhaps there is a way to signal this to them, to make them rebuild their state, but I fear it's not possible. One place where this would certainly fail is the tempus solver, where a history of the state is stores. I doubt Tempus would be ok with vectors with different maps, especially since it uses the history to build the approximation of the time derivative. And if you do level set, you probably need Tempus.

How often does the migration happen? Is it just a rebalance that you do _once in a while_ or does it happen at every iteration? If it's a "rare" event, you may think to stop the simulation and restart it. It's not really efficient (you need to rebuild all the data structures), but it may be a solution...

Sorry, I know very little about mesh adaptation...

**Comment by bgranzow** [comment]
In the context of adaptivity with a PUMI discretization, a [call](https://github.com/SNLComputation/Albany/blob/master/src/adapt/AAdapt_MeshAdapt.cpp#L311) to [Albany_APFDiscretization->updateMesh()](https://github.com/SNLComputation/Albany/blob/master/src/disc/pumi/Albany_APFDiscretization.cpp#L1425) is made to rebuild all of Albany's maps and graphs and the transfer of integration point data, and the higher-level call to adapt the problem within the adaptive solution manager appears to handle the [transfer](https://github.com/SNLComputation/Albany/blob/master/src/adapt/AAdapt_AdaptiveSolutionManager.cpp#L263) of the nodal solution back to Albany. Before the mesh is actually adapted, it looks like a size field base class is responsible for [copying](https://github.com/SNLComputation/Albany/blob/master/src/adapt/AAdapt_AlbanySizeField.cpp#L52) nodal solution data to the underlying mesh, and the MeshAdapt object is responsible for [attaching](https://github.com/SNLComputation/Albany/blob/master/src/adapt/AAdapt_MeshAdapt.cpp#L226) and [detaching](https://github.com/SNLComputation/Albany/blob/master/src/adapt/AAdapt_MeshAdapt.cpp#L317) quadrature point data to the underling mesh.

The general steps might look like:
```
1) copy nodal data to the mesh
2) copy quadrature point data from Albany to the mesh
3) load balance the mesh according to something reasonable
4) call disc->updateMesh() to rebuild a bunch of stuff Albany needs
5) copy quadrature point data from the mesh to Albany
6) copy nodal data from the mesh to Albany
```

for which all the functionality in theory exists in Albany in and around the links provided above.

Another maybe easier option would be to derive your own size field (e.g . the [SPRSizeField](https://github.com/SNLComputation/Albany/blob/master/src/adapt/AAdapt_SPRSizeField.hpp)) class in the `adapt/` directory and do load balancing instead of adapting in that class (while conditionally turning off the load-balancing that Albany currently does for adaptive problems)

**Comment by RuixiongHu** [comment]
Thanks @bartgol , it happens not a lot but even for one time step there tend to be couple of iterations. I think my advisors would insist in doing things in file but still thanks for you help.

Hi @bgranzow , I was looking at your answer and to correspond to the steps you pointed, I'm currently having a balanced mesh with all fields on it, so I should be starting only from **step 4**.

I followed the concept but get a little confused about the actual implementation since the I'm not that familiar with those calls. And here's my understanding:

What I need to do is call `MeshAdapt::afterAdapt()` which will modify Albany's storage and transfer the qp field. Then call `AdaptiveSolutionManager::adaptProblem()` to transfer the nodal field. Are these all I need to call?

I would also like to know how to get to or initialize the `MeshAdapt` and `AdaptiveSolutionManager` objects. This adaptation happens inside an evaluator instead of a problem file so I'm wondering how to initialize those class in order to call the correct member function.

Thanks I'll really appreciate any answer

**Comment by bgranzow** [comment]
I'd be pretty skeptical that resizing the mesh *inside* an evaluator would actually work. I'd worry it would resize things and then somehow later down the line other evaluators wouldn't know about that resizing.

I think you might want to try building the functionality that exists inside of functions like `MeshAdapt::afterAdapt()` yourself, and not trying to call that object directly.

**Comment by RuixiongHu** [comment]
Thanks @bgranzow for your reply. I see it's potentially dangerous to resize the mesh inside one of the evaluators.

I tried to call `APF_Discretization->updateMesh()` to take a chance. And only updating the qp states.

The first thing I observed is that the code could actually continue after I calling the `updateMesh()`. Prior to adding it, it always aborted since the MeshEntity* it is looking for is changed thus missing. But after updating the mesh it is somehow able to pass this part. 

The second thing is that the field copied into Albany is messed up. It's only correct for rank 0. I have four ranks so on the mesh, only 1/4 of the mesh has qp field correctly set up, the rest of the mapping are incorrect.

I would wonder if this is really because it's impossible to do this inside an evaluator? Or I missed some extra calls? The only call I used so far is `APF_Discretization->updateMesh()`. Since the `MeshEntity*` stored in Albany becomes valid again I wonder if there's a way to do it.

Thanks,
Ruixiong

**Comment by bartgol** [comment]
Updating the mesh inside an evaluator is conceptually wrong. Consider, for instance, a change in the mesh coordinates (the simplest mesh change we can think of). The evaluators are called on a per-workset basis. So when workset 0 is evaluated, the mesh coordinates are changed for the nodes in the workset. When a 'bordering' worsket gets evaluated, it will have a mix of old and new coordinates (namely, the points shared with ws0 will have new coordinates, while the others will have old coordinates).

More important: if I move only the points inside workset0, even if the displacement field is 'globally' conformal, I could end up with some elements that cross, generating negative jacobians and wreaking havoc.

Conceptually, the mesh should be updated before (or after) a call to `FieldManager<...>::evaluateFields`.

**Comment by RuixiongHu** [comment]
@bartgol I see. But the other thing I would like to mention is that I managed to restore the mesh back to the same partition by `parma_shrinkPartition()` from SCOREC CORE. It merge the mesh and then split it again using the default split (the same way as I was originally partitioning the mesh)

So right now I kinda have the same mesh.  All topological aspects are restored. The only thing that's different might be the memory address of each element.

So I suppose the only thing that's incompatible is the content stored in `Bucket`. Since it's still trying to look for the old `MeshEntity*`. I assume this could be generalized that this mesh entity pointer is looking for a mesh entity, which is still the same but with a different memory address. It would be great if I could update this Bucket. So anything else (cood vec, solution vector or state array) could remain untact.

**Comment by RuixiongHu** [comment]
And I forget to say that this update thing is at the end of the evaluator. All calculation has been perform  prior to it. I'm just updating the storage of the qpStateArray. I don't know if this helps.

**Comment by bartgol** [comment]
Yes, if you only migrate the issue is with the buckets (which in Albany we call worksets) distribution. The call to update mesh rebuilds them to ensure consistency, but I _think_ it should be outside the evaluator chain.

The `AdaptiveSolutionManager` class has the `adaptProblem` method, which calls the `adaptMesh` on the stored adapter. Unfortunately, it seems to never be called from inside Albany, so you can't tweak Albany to call it. But if you are using LOCA (i.e., do a continuation problem), LOCA should automatically call it (the base class is from LOCA). You mentioned timestepping, I don't know what kind of timestepping algorithm you use, but if it's a basic one, you can use LOCA for it (in its simplest form, continuation is a sort of timestepping).

If continuation does not suit your problem, we need to think about how (or, better, where) to call the problem adaptation within albany.

**Comment by bartgol** [comment]
If you use LOCA, you _may_ be in luck. I have never done anything that required adaptation, but there _should_ already be most of the infrastructure in place in Albany, inside the adapt folder.

You should check how to pass parameters to the AdaptiveSolutionManager on how to build the adapter. Then check if among the ones already implemented in the adapt folder there is one that does what you need. They are all the classes that inherit from `AAdapt::AbstractAdapter`. If you can't find one that suits your needs, you need to write your own. It should not be _too_ hard, they only have a couple of purely virtual methods...

**Comment by RuixiongHu** [comment]
Thanks for the reply, I wonder if all the steps above are those will be called by `LOCA_Epetra_AdaptiveStepper.C`?

I remember my advisor was thinking of switching to TEMPUS as time integrator in the future so I might prefer to call it somewhere by myself. 

What I wanna do is just at the end of selected time update the qp field value and return them back. If not inside an evaluator can I know where can I specify calls to initialize  tje adaptation? Since I've been mainly working on the problem.hpp files but I think all it's about is calculating evaluators. I could ask this next Tuesday if this is not what you're familiar with.

I went through files inside adapt folder, I get to know some of them but still get lost since they're really nested.  I have the feeling that everything is already in place in the folder once I could know where in the code and what's the correct order to call them. So I really appreciate any hint on how to start this up.

Thanks,
Ruixiong

**Comment by bartgol** [comment]
Again, I am not familiar with the adaptation framework. If you stick with LOCA, then I _think_ things will be called automatically for you. If you switch to tempus, the correct place where to call the adaptation would be in the PiroObserver class (I think).

**Comment by RuixiongHu** [comment]
Good morning!

Can I ask an extra question with respect to the restart functionality:

**When restarting from a mesh file, how to correctly import the already existing nodal solution field into the simulation?**

What I have is a mesh with calculated field (both nodal and qp). While restarting, all qp fields are correctly transferred into Albany. However, for solution field it always reinitialize to the initial condition if I sepecify `Initial Condition` block in the input script (I usually use `Constant`). 

But if I delete that block, it will use the nodal solution field stored in the mesh for the **first non-linear step** (**this is what I want**). However, at the second non-linear step the field value (the memory) seems gradually go wrong. So I wonder how to correctly set the calculated Solution field back to the restarted program so that it could inherit all informations left from last simulation.

Thanks!

**Comment by bartgol** [comment]
When you set `Restart Index` (or `Restart Time`), Albany should load the `solution` (or `solution_` for vector quantities) field, and use that as initial condition at the first solve. At the second nonlinear step, it should use whatever the first step produced. What solver are you using? Is the version of Albany after the unpetrification PR went in? If not, is it a Tpetra or Epetra build?

**Comment by RuixiongHu** [comment]
Good morning!

Thanks for the reply, I've figured out the problem is that I used same value for `Discretization : Restart Time` and `Stepper : Initial Time`, where Initial time should be restart time + 1 step size.

Thanks a lot for the help!
Have a nice day,
Ruixiong

**Comment by bartgol** [comment]
Great! Feel free to close when the issue is fully resolved.

**Comment by bartgol** [comment]
@RuixiongHu is this resolved?

**Comment by RuixiongHu** [comment]
@bartgol Hi I feel like this is resolved for this stage. Thanks a lot for the help!

Have a good one!
