### ISSUE TITLE
Failing Aeras test on Blake

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#532]
The following Aeras test started failing on Blake a couple days ago: https://my.cdash.org/testDetails.php?test=50932746&build=1722766 .  I think the issue has to do with this commit: https://github.com/SNLComputation/Albany/commit/710b4acd56b0538aab495f4c5d1a8727f1b14ef2 .  @mperego, I had to make the change in that commit to get Aeras compile with your changes having to do with the static graph.  Any idea on why this would be problematic?  We're just casting from CrsMatrix to Operator - I would not think that would cause an issue.

**Comment by mperego** [comment]
@ikalash Not sure. I don't understand why the cast from Tpetra_Matrix to Tpetra_Operator would fail depending on whether the graph is static or dynamic. @bartgol, do you have any clue?

**Comment by bartgol** [comment]
The cast works fine (otherwise you would get an error about it). @ikalash I'm actually surprised it compiled without that mode you linked: the type `RCP<B>&` is not polimorphic w.r.t. B (that is, iv D derives from B, you can't pass an object of type `RCP<D>` (without the reference, it would work though). So that fix should have been required long ago.

That said, this is a nasty fail. I don't see any other way than actually starting to add `printf` statements here and there, and see if something seems off. Unfortunately the error message does not help much.

Curiosity: who requests the printing of the MDField dependencies? I don't see it in my tests.

**Comment by mperego** [comment]
Oh, b.t.w. if you don't compile with `-D Tpetra ENABLE DEPRECATED CODE=OFF` (and don't do that yet because there is still a bug in Tpetra), the graph is still constructed dynamically. The graph is built with the default option (that now is dynamic profile). Before pushing the change I removed the static flag when calling the Graph constructor because at some point it will be removed from the parameters of the graph constructor and we would have to fix the code again.

**Comment by jewatkins** [comment]
@bartgol `PHAL::Setup` will print the MDField dependencies if memoization is on and graph vizualization is requested which seems to be true in this case.

**Comment by ikalash** [comment]
So it looks like this error only occurs when running ctest from a compute node, not a login node.

**Comment by ikalash** [comment]
CDash has confirmed that the issue has been resolved.
