### ISSUE TITLE
Compile errors when using stk::mesh::put_field_on_mesh

### ISSUE THREAD

**Issue by lxmota** [SNLComputation/Albany#534]
I'm not sure why we don't see this on other environments, but I have a user from USGS that compiles Albany on Scientific Linux 7.7 (very similar to RHEL 7), and there are multiple compile errors on that platform. The compiler is gcc 4.8.5, and I confirmed on a VM using Scientific Linux 7.7 that the errors are reproducible.

The relevant code lines were last touched recently (10/18) by @bartgol, so perhaps he can shed some light on what the problem might be. I attach the error log below.
---
[albany-serial-gcc-release.log](https://github.com/SNLComputation/Albany/files/3826753/albany-serial-gcc-release.log)

**Comment by bartgol** [comment]
Uh, that's weird. The code is valid. His/her compiler cannot deduce template arguments, but the first argument should already be enough, and the third argument, being nullptr, can be implicitly converted to any pointer (including the desired one, whose type is fully known, since the 1st argument implies it).

The only thing I can think of is to update the compiler. gcc 4.8 is not the best, and sometimes it comes to c++11 (and nullptr is c++11), so perhaps it's not picking up something correctly. Another thing to do would be to manually cast nullptr to the proper type (namely `double*`).

I'm sorry I don't have more to say, but this is quite strange. Again, I suggest at least gcc 5, since 4 was still dealing with c++11 additions, and sometimes it lets you down (for instance, I got issues with emplace with gcc 4.8).

**Comment by lxmota** [comment]
Ok, trying with gcc 5 or later. Thanks @bartgol
