### ISSUE TITLE
FPEs in Aeras tests on debug build

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#539]
The following Aeras tests began failing today with FPEs: 

```
Aeras_TC1_SlotCyl_implicitHV_nu0_BackwardEuler	
Aeras_TC1_SlotCyl_implicitHV_nu1e17_BackwardEuler	
Aeras_TC5_implicitHV_nu8e15_vort_BackwardEuler	
Aeras_TC5_implicitHV_nu8e15_novort_BackwardEuler	
Aeras_HydrostaticBaroclinicInstabilitiesUnperturbed_hv	
```
http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=91271 

I'm somewhat puzzled by this as I don't think there were any changes recently - or were there @mperego ?  I did not change this build to have Xpetra/Tpetra deprecated code off yet so it would not be due to that.

**Comment by mperego** [comment]
I committed this 70070688a1d47d23c718119055d872697b1c01b3, where I fixed a build error by passing `per_local_row()` instead of `per_local_row` (the former returns an arrayView). While at it I removed the 'Tpetra::StaticProfile', so, if you are not turning off the deprecated code in Tpetra, it is allocated dynamically. I don't see how this could be the issue.

Otherwise is some change in Trilinos..

**Comment by ikalash** [comment]
So I figured out my problem: my Debug Trilnos build was suppose to be all debug, but it wasn't due to this line: 

-D Trilinos_ENABLE_DEBUG:BOOL=OFF \
 
When we set the debug build to on, the FPEs reappear.  I don't know how long the FPEs were there...  Doing a backtrace is not helpful.  

Anyway, I'm punting on this right now...  if someone has time and wants to look into this, that would be quite helpful.
