### ISSUE TITLE
Changes to Albany master

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#569]
As I mentioned at the Albany weekly telecon a couple weeks ago, we are planning to make some changes to Albany master to make it easier to develop and support the code for the Land Ice application, the primary funding source for Albany currently within Sandia.  We are envisioning three "branches" of Albany going forward:

1. Albany LCM - this is in the following fork created by @lxmota : https://github.com/lxmota/Albany .  Note that SCOREC has been removed from this fork.
2. Tagged-April2020-master: we will move an April 2020 VOTD Albany master to a tag, that others (e.g. RPI, USC, @jrobbin , @gahansen ) can branch and develop from in the future.
3. Master - this will be the Albany Land-Ice (ALI) project code base, in which capabilities not needed for ALI will be pruned.

We are thinking to begin the pruning of Master (3. above) **2 weeks from now** on April 20, 2020.  Please comment here if you have any questions or concerns.  I plan to devote some time at the Albany telecon tomorrow (4/7/2020) to discuss this.

**Comment by bartgol** [comment]
Note: if something has a decent change of being useful in the future (even if not necessarily to LandIce) and requires little maintenance, it will *not* be pruned.

As Irina pointed out, our pruning is driven by the fact that LandIce is paying most of the albany core development, and the upcoming block discretizations have the potential to break a lot of code.

If you are an Albany developer, and are willing to help keep some code in master during the blocks transition, please, let me, @ikalash , or @mperego  know. We can work together so that current capabilities are maintained in master. Otherwise, due to lack of resources, we will be forced to drop some things.

We reiterate that you will still be able to build the current version of Albany, by branching from the tag that we will create.

**Comment by ikalash** [comment]
Since we have discussed this and made a decision to move the current master of Albany to a tag (https://github.com/SNLComputation/Albany/releases/tag/Old_master_support_end), I will go ahead and close this issue.

**Comment by ibaned** [comment]
Has this been discussed with people from RPI?

**Comment by lxmota** [comment]
@ibaned @ikalash I believe yes, and that RPI is also moving away from SCOREC. Not sure if they are going their own way or using my fork going forward:

https://github.com/SNLComputation/Albany/issues/574#issuecomment-617879162

**Comment by ibaned** [comment]
you mean moving away from Albany?
Well, as long as they know, that's fine.

**Comment by lxmota** [comment]
@ibaned Sorry, I meant moving away from SCOREC, as per @ikalash comment. Based on that comment, it appears they are aware, but I haven't attended the Albany meetings for a while, so I can't confirm first hand.

**Comment by ibaned** [comment]
We're in some confusion here of our own creation: SCOREC is the name of the center within RPI where the people we collaborate with work. It was probably a bad idea to name any directory or code component after an institution (which is not going away), but there it is.

**Comment by lxmota** [comment]
Right. Then it's PUMI or whatever name that mesh database has nowadays.
