### ISSUE TITLE
Timeouts in ALI tests in CUDA builds

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#572]
It looks like a couple days ago, the following LandIce tests began timing out in our CUDA builds (ride, waterman): 

```
FO_AIS_16km_MueLu
FO_Test_CircularShelf_Tpetra
FO_Test_ConfinedShelf_DepthIntBC_Tpetra
```
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=561
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=545 

I believe @jewatkins is looking at this already.  Creating the issue to document.

**Comment by jewatkins** [comment]
Those actually might be separate issues. Two of those are out of memory errors similar to the error I always get when I try to use muelu on gpus. It'd be interesting know what caused this test to start failing since it probably should have been caught sooner.

The first one might be related to the performance issue we're having on blake but I'm not sure.

**Comment by ikalash** [comment]
Maybe I should open a Trilinos issue.  It looks like the issues started on waterman on 4/8 (ride was down at the time but I'm sure it would have happened there).  I don't think we made any changes to Albany on 4/7 that would have broken things on the Albany side.

**Comment by ikalash** [comment]
This issue was resolved by adding the appropriate option under MueLu (see https://github.com/trilinos/Trilinos/issues/7149 for more info).
