### ISSUE TITLE
Sensitivity comparisons do nothing

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#594]
It appears the sensitivity comparisons do nothing in Albany.  When one sets 'Sensitivity Comparisons' to be > 1, the test is marked as passed regardless of whether the sensitivity computed matches the test value.  @mperego, are you aware of this?

**Comment by mperego** [comment]
Um, here is how sensitivities check should be set. 
```
    Sensitivity Comparisons 0:
      Number of Sensitivity Comparisons: 1
      Sensitivity Test Values 0: [1.86580896757000014e+07]
    Sensitivity Comparisons 1:
      Number of Sensitivity Comparisons: 2
      Sensitivity Test Values 0: [1.97888630229000002e+06]
      Sensitivity Test Values 1: [3.539604e+06]
```
This works. But I agree it's misleading, and we should at least throw an error when the parameters are not set correctly. It's very bad that one thinks the sensitivity is checked and correct while in reality it is not checked.

**Comment by mperego** [comment]
I edited the post above because there was an error. 
Sensitivity Comparisons "i" referes to parameter "i" (counting both scalar and distributed parameters).
If you have multiple responses than you'd have (for two responses)
`Sensitivity Test Values 0: [1.86580896757000014e+07, 1.3856]`

My understanding is that you would have `Number of Sensitivity Comparisons` > 1 depending on the layout of dgdp. For distributed parameters, you'll always have `Number of Sensitivity Comparisons = 1`, because we actually check the norm of the sensitivity rather than the entries. However, if you had aggregated scalar parameters, than I think you could have  `Number of Sensitivity Comparisons > 1`. @bartgol do you agree?

**Comment by ikalash** [comment]
Ah I see, my syntax wasn't quite right.  We should definitely add the error throwing if there is a syntax error in how the sensitivities are specified.

**Comment by ikalash** [comment]
It looks like for scalar parameters and a scalar response, here is the syntax for checking the comparisons:
```
 Regression Results:
    Number of Comparisons: 1
    Test Values: [-4.391538524980e+01]
    Sensitivity Comparisons 0: 
      Number of Sensitivity Comparisons: 2
      Sensitivity Test Values 0: [0.0] 
      Sensitivity Test Values 1: [5.62650000000000025e-02]
    Relative Tolerance: 1.00000000000000002e-03
    Absolute Tolerance: 1.00000000000000008e-05
```

**Comment by mperego** [comment]
It makes sense to me because the scalar parameters are usually lumped in one vector parameter. How the `Parameters` sublist looks like in this case?

**Comment by ikalash** [comment]
Here's the input file: https://github.com/SNLComputation/Albany/blob/master/tests/small/Thermal2D/input_with_source.yaml .  Anyway, I'll close this issue and open a new one regarding throwing errors when specifying incorrect syntax for sensitivity comparisons.

**Comment by bartgol** [comment]
@mperego what you said seems correct to me.
