### ISSUE TITLE
New failures in clang debug build

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#599]
We have a bunch of new failures in the clang debug build: 

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=2409

Here is how the error looks like: 

```

p=3: *** Caught standard std::exception of type 'std::logic_error' :

 /projects/albany/nightlyAlbanyCDash/repos/Trilinos/packages/thyra/core/src/support/operator_vector/adapter_support/Thyra_DefaultSpmdMultiVector_def.hpp:195:
 
 Throw number = 1
 
 Throw test that evaluated to true: !(nonnull(localValues))
 
 Error!

p=2: *** Caught standard std::exception of type 'std::logic_error' :
 /projects/albany/nightlyAlbanyCDash/repos/Trilinos/packages/thyra/core/src/support/operator_vector/adapter_support/Thyra_DefaultSpmdMultiVector_def.hpp:195:
 
 Throw number = 1
 
 Throw test that evaluated to true: !(nonnull(localValues))
 
 Error!
```
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=208383&build=2409

I'm thinking it's due to Trilinos changes, but I can double check if it's my PR that got merged in yesterday.

**Comment by ikalash** [comment]
I fixed it.  It did have to do with my PR.

**Comment by ikalash** [comment]
@mperego : I'm a little bit confused about the behavior of DEMO_PDES.  I turned off DEMO_PDEs in my nightly on mockba, which you can verify here: https://sems-cdash-son.sandia.gov/cdash/viewConfigure.php?buildid=3026 .  However, it appears the DEMO_PDEs still get built/run: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlypassed&buildid=3026 .  About 31 tests got turned off when I turned off Demo PDEs, so it did something, but I would expect a lot of the tests that still get run to be lumped in DEMO_PDES, e.g. the Heat ones, the Ioss ones, etc.

**Comment by mperego** [comment]
Yeah, my understanding is that there are some "basic" problems that are always run. We should probably revisit this at some point and decide whether we should move all those tests into the DEMO_PDEs group, or have another group, e.g. called "BASIC_PDEs" or similar.

**Comment by ikalash** [comment]
I see.  I was thinking all these tests would be classified as demo pdes.

**Comment by bartgol** [comment]
Yes, that's correct. I think the idea (at least when Albany was a large project, with many physics packages) was to make sure some basic tests were always run, no matter what. Whether that's desirable or not, it is debatable. Ideally, the basic Albany should run some _unit_ tests, rather than only system tests, so that detecting bugs becomes easier.

I have no strong feeling either way (meaning put all PDEs in DEMO_PDES or leave some built regardless). When I develop something that touches core albany files, however, I often turn _everything_ off (to speed up compilation), and start debugging only the Heat prroblems. When those are good, I start turning on DEMO and LANDICE.

**Comment by bartgol** [comment]
@mperego Are you suggesting to simply create a new Label to group certain tests or to actually put some cmake logic to disable building certain files? The former is obviously ok regardless of how we feel about those tests. The latter seems poinless, since we already have a DEMO library, so we could stuff everything in there.

I'm assuming you meant the former. I'm ok with that. But at this point, I'd recycle the DEMO label (which will then contain a different number of tests depending on whether ALBANY_DEMO_PDES is enabled or not).

**Comment by mperego** [comment]
@bartgol I guess that having labels that are not consistent with the cmake logic is even more confusing. I think we first should decide if we want two sets of tests, one with more basic tests (possibly always run) and one with more exotic tests (the DEMO_PDEs), or only one set of tests.

**Comment by bartgol** [comment]
True.

To be fair, I'm fine keeping 1 (or maybe 2, one steady, one unsteady) problems always run even when ALBANY_DEMO_PDES is OFF. It helps debugging, and gives a ready-to-go example for someone who might download the software and try to run something (without knowing much about all the cmake options).
