### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by ibaned** [SNLComputation/Albany#60]
breakaway from #58, so far `epetra` and `issue-34` are known to be branches we should keep.

**Comment by ibaned** [comment]
Here are the branches I'm planning to remove and their current hashes, so they can be recovered in the near term if someone needs one of these:
```
layer_add_bug 2426b3b1cf26e7a3f2fcd2e6400ed69ab02a674b
preDynRankViewBranch 69a9c76d3c62a12cafab0a16ea5de2d0d64803ed
FelixCoupling 47021ff37e4e117b11bbd1dae46dc9797bb6e514
boundary_mesh 86706b6ec47e37afe1234104addbae993fd252a6
albany_felix_mismip 42a105e4802c99dbaba4eda23330ece1ea90faca
FELIX_Temperature 271f34c2dd9f7702fcfa38ee743bf59e9de0580b
sideset_equations 4d0a4680c87e9d67676e43adb31e4d6e41111b34
```

**Comment by ibaned** [comment]
Those branches are gone, so for now I think I can close this. The remaining branches are:
```
master
gh-pages
issue-34
sideset_equations_cleanup
epetra
```
The first two are needed, the second two should be merged soon (@bartgol is that true for `sideset_equations_cleanup` ?) and `epetra` will be the subject of a later issue.

**Comment by bartgol** [comment]
Thanks Dan!

boundary_mesh was mine and I forgot to delete it. sideset_equations was also mine, but only the _cleanup version is the one that matters now.

**Comment by mperego** [comment]
Thanks Dan.

I was using preDynRankViewBranch for some large scale optimization runs as there are some fixes to be done in the case MeshScalarT is a Fad type. Anyway I'm almost done with those fixes in master so probably it is OK to have it removed from the repo. The other reason I was keeping it is to compare performances before and after the DynRankViewBranch refactoring. Anyway, I'll push the branch back if I need it.

albany_felix_mismip was used by guys in LANL for a benchmark study. I think they are done now.. since a couple of weeks. So it is OK to have them removed.

**Comment by bartgol** [comment]
I'd like to cleanup again a bit the repo, and remove some of the stale branches. Please, take a look at the branches, and see if any of those need to be kept. I was thinking of purging branches 2+ years old. Right now, these are

- epetra
- dbcs
- always-64-bit
- FELIX_Enthalpy
- revert-270-master
- revert-271-revert-270-master

If noone objects, I'll purge them at the end of the month.

**Comment by lxmota** [comment]
@bartgol dbcs branch is stale. Forgot to remove at some point.

**Comment by ikalash** [comment]
Please do not remove epetra.  It has the original history of Albany (which got wiped when we merged tpetra in awhile ago).  I refer back to it from time to time.

**Comment by mperego** [comment]
@bartgol I removed the FELIX_Enthalpy branch
