### ISSUE TITLE
Trilinos/Albany clang build issue on CEE

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#620]
It looks like there is a build issue having to do with Teuchos in our Clang CEE build.  I did switch our clang compiler over the weekend, so it could be due to that, rather than due to a change in Trilinos.  I'd like to open a Trilinos issue, but maybe someone could look at the issue in addition to me as a sanity check?  Here is the Trilinos build error: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=4560 , and the Albany one: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=4563 .  What's weird is that the Trilinos "errors" look to me to just be warnings, and the build appears to complete.  But then Albany complains about an issue with the teuchos library, suggesting it was not built correctly.  I also have a strange feeling of deja vu, that I have encountered this before, but can't remember when.  

Any thoughts from anyone?

**Comment by ikalash** [comment]
I should add, I am using clang 10.0.0 now compared to clang 9.0.1 before.  @gahansen didn't we have this same discussion once when you were rebuilding TPLs actually, not long ago?  Maybe the thing to do is to go to clang 9 - I think it's what we did before.  It is sad that already I don't remember the details...  getting old I guess... :(

**Comment by mperego** [comment]
> I should add, I am using clang 10.0.0 now compared to clang 9.0.1 before. @gahansen didn't we have this same discussion once when you were rebuilding TPLs actually, not long ago? Maybe the thing to do is to go to clang 9 - I think it's what we did before. It is sad that already I don't remember the details... getting old I guess... :(

Why did we switch to Clang 10? I thought we agreed that it would be better to stick with Trilinos compilers as much as possible. That's why we (@ikalash in particular) pushed trilinos to have a Clang build for PR testing.

**Comment by ikalash** [comment]
I forgot what we decided and when I switched to sems modules, I just picked the most recent one.  I will try going back to 9.  Hopefully that will fix it.  

Sorry, guys, too many builds / compilers to keep track of, sigh...

**Comment by gahansen** [comment]
I think that your Trilinos build completed fine. I am using my own version of Clang 10 and the TPLs that I built, and I usually see warnings that look like these. The clang compilers are chatty and warn about things that gcc does not; I don't see anything in my current warning set (or yours posted) that is of concern.

I think your Albany build is linking to the wrong library somewhere. As I read the link errors in the Albany build, it looks like the compiler you used to compile the files needed for yaml2xml used 'basic_ostringstream()@GLIBCXX_3.4.26' When you linked this file to make the executable, the 'ld' command cannot find that version of basic_ostringstream in the libraries that it is using. I interpret this as the compiler using different libraries than the linker.

This is the mess that we ran into when we gave up using my TPLs and compilers in favor of the SEMS ones a while back - in that case then we were getting the wrong TPL libraries when we linked versus what we compiled against and we had some tests fail. I think you are seeing symptoms of that same issue again.

Probably the easy thing to do is to switch back to clang-9 and hope this disappears. I dealt with it in my personal builds by making sure that the compilers, linkers, Trilinos, and Albany all link with the same, consistent, versions of libraries and TPLs built with the same tools. I worry that this issue will continue to crop up in mysterious ways until we do that - we are working with a very complex software system with a lot of dependencies maintained by a lot of different people with different needs. We usually see this on CEE first because of so many projects having different versions of similar things - it is hard to know what you are getting across all the modules and custom variations of PATH and LD_LIBRARY_PATH (especially when you work on many different projects using different versions of things like we all do).

**Comment by ikalash** [comment]
Thanks @gahansen for the diagnosis - that makes sense that it's a TPL / linker error, and it's all coming back to me now from before.  I wonder if for whatever reason the nightly build is finding some of the old pre-built TPLs instead of the sems ones?  I think you had a way to ensure that right TPLs were used by setting a Trilinos option - can you please remind me what it is?  Was it something with RPATH?

**Comment by gahansen** [comment]
Our nightlies that start with 'cron' will start with a clean environment. I'd suggest that we 'include' a file, right at the beginning, that sets up all the 'test specific' variables - compilers, libraries, TPL paths - everything needs to be explicitly set instead of loaded in externally from modules, PATHs, or LD_LIBRARY_PATHs.

We need to have TPLs built with the same compiler and MPI version we are using to build Trilinos and Albany - I did that in my personal builds finally to get rid of the mess we had a while back. If we use a netcdf library from Sierra, SEMS, or Alegra or what have you, we have no idea what LIBGCC that was built to need - it depends on the compiler that the person who built it used. Plus we dont know if the person who build it made the changes that Seacas needs to support large files. 

I used to use only Sierra built stuff for my Trilinos and Albany builds because they managed their environment that way - everything they needed was built by them using the same tools for each version of the code they supported. It was compilicated though and I needed to learn what they were doing as we went along.

We could use either LD_LIBRARY_PATH or RPATH to control what 'ld' links to. I like the RPATH as you can build different versions of each library and not have to continuously modify your LD_LIBRARY_PATH. We could do it either way in the nightly tests though.

**Comment by gahansen** [comment]
I did not completely answer your question. In my build scripts, say:

Albany/doc/cee/do-cmake-trilinos-cee-clang10

I have lines like:

    -D Netcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
    -D Netcdf_LIBRARY_DIRS:PATH=$NETCDF/lib \

I hardcode the locations for $NETCDF above this. However, you also need to carefully look at the CMake configure output and make sure that it finds this correctly and does not load something else. Anything that is loaded by Trilinos with a FIND_PACKAGE() is subject to the search path that FIND_PACKAGE() sees. The hardcoded path will usually overrride that, unless there is a typo or problem. In that case, CMake will silently load something else and you will not see it unless you look carefully at the configure output. I set the RPATH for the Trilinos executables with the variable:

    -D Trilinos_EXTRA_LINK_FLAGS:STRING="-L${LIB_DIR}/lib -L${LIB_DIR}/lib64 -lnetcdf -lpnetcdf -lhdf5_hl -lhdf5 -lz -lgfortran -Wl,-rpath,${GCC_LIB_DIR}/lib:${GCC_LIB_DIR}/lib64"

Here again I am hardcoding the location of the libstdc++ library that I want the executables to use ( ${GCC_LIB_DIR})

**Comment by gahansen** [comment]
In the above ${LIB_DIR} is a superset of ${GCC_LIB_DIR} as the TPL libraries are not always contained in ${GCC_LIB_DIR} (SUPERLU for example). But maybe they should be?

**Comment by ikalash** [comment]
Thanks, Glen, i remember now.  The weird thing is I am not setting any of the lib dirs anymore, like you were before, to any pre-built TPLs, since I am using the sems modules for those.  I also don't have any FIND_PACKAGE() lines anywhere.  I am wondering if it's somehow picking them up in a different way, though I'm not sure how.  I am going to check what happens if I build from scratch using cmake rather than using the cdash scripts, as a sanity check.  

In my case, RPATH should point to the dirs where the sems TPLs are, correct?  So it would be something like ``-rpath,$ENV{NETCDF_LIB_DIR}:$ENV{HDF5_LIB_DIR}:$ENV{BOOST_LIB_DIR}" ?

**Comment by gahansen** [comment]
You can probably deduce what is happening by looking at the Trilinos configure output. Modules are a nice convenience feature, but if, say the TPLs in that module are compiled using a different compiler module than you want to use - everything falls apart. There should probably be only a single module for everything - that has it in the compilers used to build the dependencies (the TPLs) within that module. This would have the same effect as the 'include file' I mentioned above. Problem is - we need to get the people building the module to understand what we are doing and why to convince them to do that, and this is all very complex as we see here.

On CEE - if you (from a clean environment):

module load sntools/master

I think it sets everything you need in a consistent fashion if memory serves.

We could do this with modules fairly easily I think.

The problem with specifying all the libraries on the RPATH is that they all need to be compiled to work together with the same compiler and MPI - and then it is easiest to stick them in the same directory. Otherwise, it will drive us crazy to keep track of all this.

**Comment by gahansen** [comment]
If you do a stand along build, please look at the filesystem under:

/projects/albany/clang-10.0.0

Everything under there is built and compiled with the same compiler and mpi (clang-10.0.0 and Open MPI 4.0.1 I think). Boost, all the include files, and all the TPL libraries are in there. If you link to that, you only need one include dir for the whole system and one LIB dir for the whole system. If you do not link to anything else (clean up your PATH and have it include only /projects/albany/clang-10.0.0/bin with a LD_LIBRARY_PATH=/projects/albany/clang-10.0.0/lib:/projects/albany/clang-10.0.0/lib64)

You should get a clean build and set of tests because everything is consistent. I had to do that when we ran into the mess awhile back, but it has worked great for me so far.

**Comment by ikalash** [comment]
Thanks, Glen.  It looks like this was due to a really silly error I made while refactoring the nightly scripts over the weekend.  I was having all the builds point to the same gcc Trilinos install, hence the mismatch b/w compilers.  The upshot with using the sems modules is that one should need to set the extra link flags and RPATH.  Anyway, I will close the issue.  Hopefully everything will be clean tomorrow.
