### ISSUE TITLE
Track down Epetra/Tpetra performance differences

### ISSUE THREAD

**Issue by ibaned** [SNLComputation/Albany#63]
In #58 @ikalash mentioned that the `epetra` branch is still used because it is faster. Is it possible to create a FELIX example problem with both Epetra and Tpetra configurations that clearly shows the performance difference so we can investigate ? With the momentum towards Tpetra, I think its really important that we put effort into Tpetra performance.

**Comment by mperego** [comment]
I don't use anymore epetra branch because it does not contain several recent progresses.

My understanding is that the multigrid preconditioner we use for ice sheets large-scale simulations, would not work as well in Muelu because line solves (if I remember correctly) are slow compared to ML ones. This has nothing to do with Albany though.

**Comment by ibaned** [comment]
Although it may not be Albany's fault, any serious performance degradations from Epetra to Tpetra are a risk to Albany's success and we should try our best to identify the root causes and work with Trilinos developers to fix them. Is it possible to set up an Albany example that demonstrates the time difference in line solves between ML and MueLu ?

**Comment by ikalash** [comment]
Here is an email from me to Irina Demeshko sent in July 2015 detailing the slow-downs that were observed:

************************************************

From: Tezaur, Irina
Sent: Thursday, July 16, 2015 10:12:05 PM
To: Demeshko, Irina Petrovna (-EXP)
Subject: Albany timings
 

Hi Irina,

 

Earlier this week, Ray Tuminaro was making some runs of some ice sheet problems using Albany on Hopper and noticed that the run times are substantially lower than when he was running the epetra branch of Albany a few months ago (900 seconds vs. 750 seconds).  I believe this is largely due to changes in Trilinos in the past few months.  I spoke with Roger Pawlowski about it today and he had a few ideas on what might be causing the slowdowns, which led to some questions for you:

 

1.)    Has the runtime array been eliminated from Albany?  I guess Roger wrote an MDField code that gets dynamically the rank, which can cause slowdowns. 

2.)    Apparently there is an issue in Intrepid when using BLAS/LAPACK.  Some routines are inefficient due to usage of the parens operator.  Would Albany be using any of these kernels?

 

Thank you,

 

Irina

*****************************
I still has this email in my inbox, since it was never resolved.  I feel like it would be nice to get to the bottom of this difference in performance, but unfortunately I do not have the time and FELIX dos not have the funds.   

Here was Irina Demeshko's reply to my email above: 

"The slow-down should be exactly due to the fact that run-time implementation of MDFieald is slow now and we don't currently use Blas/Lapack kernels in Intrepid.
Since Kokkos View doesn't support runtime rank, we do some additional computations to work around this issue in Phalanx. Therefore, we recommend to use runtime runk MDFields only when necessary.

Conserning BLAS/Lapack: we desibled them temporary ( they didn't work with Kokkos) and will be able to use them in Intrepid very soon (we almost finished our Kokkos-to-Blas/Lapack interface)"

**Comment by mperego** [comment]
@Dan I guess so. At the moment I don't see this as a priority since MueLU guys are well aware of this issue and I don't have money/time to work on this. I think that finishing the conversion of Albany to Tpetra (in particular regarding sensitivities/optimization for distributed parameters) should have higher priority than this. Although for both of these issues, we can hardly use FELIX funds (and we might need to wait until July for new funds to come in).

**Comment by mperego** [comment]
@ikalash I think that conversation is a bit obsolete now because a lot of things changed after the introduction of DynRankView and refactoring of Intrepid2. Not that performance issues are gone.. Actually I think we cannot hope to beat previous implementation on serial runs. Portability has a price. What we should keep monitored is whether the overhead introduced by the new changes is acceptable for serial runs.

**Comment by ibaned** [comment]
Okay, well if this is seen as an expensive task that there isn't much funding for right now, we can put it on hold. However, as long as people are thinking of keeping Epetra in any form, either as a branch or as a compile option, for performance reasons then this issue is important and should remain open.

**Comment by ikalash** [comment]
@mperego , I agree 100%.  What I was getting at is the epetra branch may help identify things that are slower in the current code; but a lot has changed since the epetra branch was last working in Albany as well as Trilinos so an apples-to-apples comparison may not be possible regardless.  I'm OK removing the epetra branch if people think this is the best path.  I just wanted to document the observed differences in speed between this branch and the master branch.  

@ibaned , I think for FELIX, we cannot remove the epetra compiler option -- we need an ML preconditioner for some of our runs that is not as fast in MueLu.

**Comment by ibaned** [comment]
I would say the ML versus MueLu difference with the latest Albany version counts as part of this issue. Its fine if you don't have time/funding, but is it possible to create an example that compares the ML and MueLu preconditioners for one of these runs ?

**Comment by aprokop** [comment]
If I recall correctly, the slowdown was due to the slowness of Ifpack2 for line smoothing. I think this was also shown in some MHD problems. Brian Kelley has done a lot of work last year to refactor and speed things up, so it may be a good idea to rerun the experiments comparing line smoothing in MueLu vs ML.

**Comment by ibaned** [comment]
Thanks @aprokop, this is exactly why I want a comparison case, because work is being done to address these things and we need something to monitor the status and either declare success or identify the current bottleneck.

**Comment by ikalash** [comment]
@ibaned : Yes, I can create an example that compares ML and MueLu on a FELIX problem.  I will create a separate issue for this.
