### ISSUE TITLE
Basis functions layout perf question.

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#649]
I am wondering whether we could squeeze a tiny bit of perf out by swapping the BF layout, from (cell,node,qp) to (cell,qp,node).

The reason is that our for loops structure is like
```
for (int cell ...) // This is the (only) dim where we ||ize on with kokkos, btw
  for (int qp ...)  // Integration
    for (int node ...) // to compute qp value
```
So it might be best for caching purposes to make node striding faster. That is, assuming our layout is LayoutRight (at least on host). I guess on GPU the current layout is fine, since I'm assuming PHX uses LayoutLeft there...

@jewatkins do you have any thoughts?

**Comment by jewatkins** [comment]
I haven't really looked at changing the layout or inner loops. Having the nodes contiguous on host (no openmp) would help the loop you mentioned because of caching. In general, there should be a trade off between the two layouts depending on the contraction. For interpolation where we contract on nodes, it's better to have (qp, node) but for integration where we contract on qp, (node, qp) is better. There's also other tricks we can do depending on the order of quadrature and element type. Ideally, we would create an abstraction to handle the various cases depending on what's more important. It's on the todo list but it's not really high priority right now since the assembly isn't as expensive as the solve.

I did spend a brief time cutting down the memory requirement from the basis functions. It's on a branch. When/if I get back into it, maybe I'll spend some time looking at the layout too.

**Comment by bartgol** [comment]
Ah, I had the impression BF were always having node loop being the inner one, but I was wrong.

Ok, I'll close this then.
