### ISSUE TITLE
 SteadyHeatConstrainedOpt2D_Scalar_And_Dist_Param_Tpetra failing on Blake in GCC Warning-free build

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#663]
With this nightly test harness being back up, it appears the  SteadyHeatConstrainedOpt2D_Scalar_And_Dist_Param_Tpetra  test is failing in the Blake GCC warning-free build: 

https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=878186&build=12561 

The error is a bit cryptic:

```
 		total iterations: 39
  
resp<Tangent>: 0.221462 [ 0 0 0 ]
resp<Tangent>: 0.15 [ 0 0 0 ]
resp<DistParamDeriv>: 0.221462 [ 0 0 0 0 ]
resp<DistParamDeriv>: 0.15 [ 0.075 0.075 0.075 0.075 ]

p=0: *** Caught an unknown exception

p=1: *** Caught an unknown exception

p=3: *** Caught an unknown exception

p=2: *** Caught an unknown exception
```

@mperego, @kliegeois : any idea on what might be going on?  It could conceivably be a fluke, in which case we can give it another day and see what happens tomorrow.

**Comment by mperego** [comment]
@ikalash I'm not sure. @kliegeois found out that it failed when Sacado is built with debug checks. Anyway, @kliegeois is going to modify the implementation using `SharedParameter`,  so instead of looking into fixing this, I think it's best to wait for the new implementation that should happen next week at the latest.

**Comment by kliegeois** [comment]
@ikalash this looks very similar to the issues that I faced. As proposed by @mperego , it is better to wait for the use of SharedParameter as this might solve the issue.

**Comment by ikalash** [comment]
Thanks @kliegeois .  Do you know what is the approximate timeline for the SharedParameter fix?

**Comment by kliegeois** [comment]
@ikalash, I do not know yet. I am on it but it requires some refactoring. Hopefully, I should be able to estimate the timeline soon.

**Comment by kliegeois** [comment]
@ikalash the issue is resolved on my branch.

Before creating the PR (which includes the Hess-vec computation with scalar parameters), I still need a bit of time to: 
- fix 3 tests that failed,
- build with warnings as errors,
- finalize the dox.

The PR should be created early next week at the latest.

**Comment by kliegeois** [comment]
@ikalash quick update: the PR should be ready on Monday!

**Comment by ikalash** [comment]
Great thanks @kliegeois !  I will keep an eye out for it next week.

**Comment by kliegeois** [comment]
@ikalash is the issue fixed?

**Comment by ikalash** [comment]
Yes it was - sorry, I forgot to close the issue earlier.

**Comment by kliegeois** [comment]
@ikalash great, thanks a lot!
