### ISSUE TITLE
Failing FO_GIS_CoupledThickness tests in nightlies due to FPEs

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#678]
It appears a couple days ago the FO_GIS_CoupledThickness tests began failing on several platforms in the nightlies due to FPEs, e.g. 

```
Phalanx writing graphviz file for graph of NFM0Residual (detail = 1)
 Process using 'dot -Tpng -O phalanxGraphNFM0Residual
 ************* Phalanx Setup **************
 ************ Evaluation Types ************
   NFM0Residual
   DFM0Residual
   RFM0HessianVec_surface_velocity_mismatch
   RFM0Residual_surface_velocity_mismatch
   RFM0Jacobian_surface_velocity_mismatch
   FM0Residual
   RFM0DistParamDeriv_surface_velocity_mismatch
   RFM0Tangent_surface_velocity_mismatch
 
 ******************************************
[cee-compute022:29070] *** Process received signal ***
[cee-compute022:29070] Signal: Floating point exception (8)
[cee-compute022:29070] Signal code: Invalid floating point operation (7)
[cee-compute022:29070] Failing at address: 0x7fb783d9b87f
[cee-compute022:29071] *** Process received signal ***
[cee-compute022:29071] Signal: Floating point exception (8)
[cee-compute022:29071] Signal code: Invalid floating point operation (7)
[cee-compute022:29071] Failing at address: 0x7fd1912a687f
[cee-compute022:29073] *** Process received signal ***
[cee-compute022:29073] Signal: Floating point exception (8)
[cee-compute022:29073] Signal code: Invalid floating point operation (7)
[cee-compute022:29073] Failing at address: 0x7f2679fd587f
[cee-compute022:29070] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7fb784fec630]
```
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=978566&build=14125 

It happens for both the epetra and tpetra version of the test.  Not sure who is the culprit here...  @mperego and @bartgol , I'm guessing you might know?

**Comment by mcarlson801** [comment]
Sorry about the late response on this, it looks like this one is on me. These two tests were ones Jerry and I were concerned about failing with my sideset memory changes. I checked to make sure they were working before and after I pushed those changes but I guess something changed with recent PRs that uncovered a sneaky bug.

I reverted the sideset memory change and these tests are passing now. I'll look further into the actual cause.

**Comment by ikalash** [comment]
Thanks, @mcarlson801 !

**Comment by ikalash** [comment]
Unfortunately these are still failing.

**Comment by bartgol** [comment]
Is this passing now? I still get an FPE on my workstation...

**Comment by ikalash** [comment]
Yes, the nightlies were clean.

**Comment by bartgol** [comment]
Interesting. I did ran valgrind, and no error came up, so if it fails once, it should always fail. I'll run again, and make sure my master is up to date.

**Comment by jewatkins** [comment]
These are failing again

**Comment by bartgol** [comment]
I am puzzled on why they sometimes fail and sometimes don't.

**Comment by jewatkins** [comment]
@mcarlson801 is going to investigate to see if it has to do with the collapsed sidesets. We noticed that it started failing (on/off) after they were turned on for the CoupledThickness problem so it's possible there may be some correlation.

**Comment by ikalash** [comment]
These tests are still failing and it has been awhile.  Any update on the status and how long it will take to fix the tests?

**Comment by mcarlson801** [comment]
> These tests are still failing and it has been awhile. Any update on the status and how long it will take to fix the tests?

Now that my university deadline has passed, I have time to look at this on my end. I'm still not sure what the cause is and I'm having trouble replicating the error in a situation where I can run it through a debugger. I'll update later today when I've tried a few more things.

@bartgol Any ideas? The bug didn't go away when I reverted my memory changes so I assume it has to be an interaction between my StokesFO sideset changes and your big pull request.

**Comment by bartgol** [comment]
Not off the top of my head. I will try to run and see what the culprit is.

Sorry, I forgot about this issue.

**Comment by mcarlson801** [comment]
It looks like my change to GenericMeshSTKStruct to get the workset size max from the discretization parameters if it was missing from the side set discretization was the culprit. I'm not exactly sure why it was causing it to fail so I'm going to look into it. I pushed a change that should fix the nightlies in the meantime.

**Comment by ikalash** [comment]
Thanks for tracking this down, Max!  I'll have a look at the nightlies tomorrow to see if the issue is fixed.

**Comment by mcarlson801** [comment]
The issue was being caused by this block of code in GenericMeshStruct.cpp (removed in my most recent commit from line 517)

`if (!params_ss->isParameter("Workset Size")) {
  int worksetSizeMax = params->get<int>("Workset Size", DEFAULT_WORKSET_SIZE);
  params_ss->set("Workset Size", worksetSizeMax);
}`

The purpose was to use the maximum workset size from the discretization parameters if the side set discretization didn't have it. This is the behavior for other mesh struct types (ExtrudedSTKMeshStruct for example) so the idea was to make the behavior consistent and enable slim sideset memory allocation.

It isn't clear to me at the moment why this change was making things fail. Running in a debugger hinted that memory was being corrupted long before the actual segmentation fault or FPE. I was unable to run with Valgrind since I was getting illegal instruction exceptions that seemed to be related to OpenMPI.

**Comment by mperego** [comment]
@mcarlson801 thanks. I'll try to have a look into it at some point.
