### ISSUE TITLE
SideSetLaplacian_3D failure on skybridge

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#681]
Looks like we have a new failure on skybridge, SideSetLaplacian_3D.  The error seems to have to do with the memory space: 

```

p=1: *** Caught standard std::exception of type 'std::runtime_error' :

 Kokkos failed to allocate memory for label "diff_1".  Allocation using MemorySpace named "Host" failed with the following error:  Allocation of size 2.216e+09 G failed, likely due to insufficient memory.  (The allocation mechanism was the Intel _mm_malloc() intrinsic.)
 
 Traceback functionality not available
 

p=3: *** Caught standard std::exception of type 'std::runtime_error' :

 Kokkos failed to allocate memory for label "diff_1".  Allocation using MemorySpace named "Host" failed with the following error:  Allocation of size 2.216e+09 G failed, likely due to insufficient memory.  (The allocation mechanism was the Intel _mm_malloc() intrinsic.)
 
 Traceback functionality not available
```

https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=988646&build=14312 

@mcarlson801 I am guessing this is related to your changes?

**Comment by mcarlson801** [comment]
The issue here seems to be that the "diff_1" view in PHAL_ResponseSquaredL2DifferenceSide is allocated to be of length dims[3] where dims is the vector of dimensions for the field layout. However, for this test, field rank is set to be scalar which means the field layout is "qp_scalar" which doesn't have 4 fields. It seems to me that this should be failing as a segmentation fault but instead is getting a value from unallocated memory. This is how it worked prior to my changes as well. Have there been other tests that use the "Squared L2 Difference Side" response with Scalar field rank?

**Comment by ikalash** [comment]
@bartgol is likely the most familiar with the Squared L2 Difference Side response - he might be able to provide more info.

**Comment by mcarlson801** [comment]
> @bartgol is likely the most familiar with the Squared L2 Difference Side response - he might be able to provide more info.

Thanks, I actually found a bug and it was my changes after all. My bad. I'll test and push the fix shortly.
