### ISSUE TITLE
Failing PyAlbany tests

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#732]
The following PyAlbany tests began failing yesterday:

```
PyAlbany_Inv_SteadyHeat
PyAlbany_Inv_SteadyHeat_MPI 
PyAlbany_multiple_SteadyHeat
PyAlbany_multiple_SteadyHeat_MPI
PyAlbany_SteadyHeat
PyAlbany_SteadyHeat_MPI
PyAlbany_SteadyHeat_StateMap
PyAlbany_SteadyHeat_StateMap_MPI
```

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=21060 

@kliegeois could you please have a look at this?

**Comment by kliegeois** [comment]
Oh those should be fine now.
I was wrong, it is not due to my commit of yesterday; the commit of yesterday solved that actually.
The NB used the commit 5a3949ca20991abacb69b192e06feee9816e3a00 and not e6b6f0994180211009a7b856e71bcc295a6b24f3 .

If it is fine with you, let's wait for the results of tonight.

**Comment by ikalash** [comment]
No problem - thanks for looking at it @kliegeois .  I'll close this issue tomorrow if it is indeed resolved.

**Comment by kliegeois** [comment]
Perfect! Thanks.

**Comment by kliegeois** [comment]
It seems to be fine :smile:

**Comment by ikalash** [comment]
Yes, thank you!  Closing now.
