### ISSUE TITLE
Failing SHMIP test on mockba

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#741]
It appears this SHMIP test began failing on one of my machines, mockba, a few days ago:

https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1502785&build=22303

Looks like it's timing out.  I'm not familiar with this test.  Anyone have any idea on what might be going on?

**Comment by bartgol** [comment]
Suite A1 is the hardest to converge, due to the input data. The log seems cropped, so maybe it is a timeout. I have been struggling to make this test faster, but the SHMIP specs are what they are, and I can't change them. Perhaps we could disable the test by default, or move the SHMIP suite to the `tests/large` folder altogether?

**Comment by ikalash** [comment]
Thanks for the info @bartgol .  It looks like the test is passing now again (it was timing out before), so I'll close the issue.  Not sure what was going on earlier...

**Comment by bartgol** [comment]
It might be that they are close to the timeout limit in starndard conditions, and that day somehow, the workstation was doing some routine update, or had the filesystem slower, or simply was not in the mood, and it slowed down a bit.
